// <auto-generated />
#pragma warning disable 1570, 1591

using System;
using Microsoft.ML.Probabilistic;
using Microsoft.ML.Probabilistic.Distributions;
using Microsoft.ML.Probabilistic.Factors;
using Microsoft.ML.Probabilistic.Collections;

namespace Models
{
	/// <summary>
	/// Generated algorithm for performing inference.
	/// </summary>
	/// <remarks>
	/// If you wish to use this class directly, you must perform the following steps:
	/// 1) Create an instance of the class.
	/// 2) Set the value of any externally-set fields e.g. data, priors.
	/// 3) Call the Execute(numberOfIterations) method.
	/// 4) Use the XXXMarginal() methods to retrieve posterior marginals for different variables.
	/// 
	/// Generated by Infer.NET 0.3.1912.403 at 15:26 on woensdag 20 januari 2021.
	/// </remarks>
	public partial class Model_EP : IGeneratedAlgorithm
	{
		#region Fields
		/// <summary>Message to marginal of 'anyTrue'</summary>
		public Bernoulli anyTrue_marginal_F;
		/// <summary>Message to marginal of 'bernoullies'</summary>
		public DistributionStructArray<Bernoulli,bool> bernoullies_marginal_F;
		/// <summary>True if Constant has executed. Set this to false to force re-execution of Constant</summary>
		public bool Constant_isDone;
		/// <summary>Field backing the NumberOfIterationsDone property</summary>
		private int numberOfIterationsDone;
		/// <summary>Message to marginal of 'orTrue'</summary>
		public Bernoulli orTrue_marginal_F;
		/// <summary>Message to marginal of 'vbool__1'</summary>
		public DistributionStructArray<Bernoulli,bool> vbool__1_marginal_F;
		/// <summary>Message to marginal of 'vbool28'</summary>
		public Bernoulli vbool28_marginal_F;
		#endregion

		#region Properties
		/// <summary>The number of iterations done from the initial state</summary>
		public int NumberOfIterationsDone
		{
			get {
				return this.numberOfIterationsDone;
			}
		}

		#endregion

		#region Methods
		/// <summary>
		/// Returns the marginal distribution for 'anyTrue' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public Bernoulli AnyTrueMarginal()
		{
			return this.anyTrue_marginal_F;
		}

		/// <summary>
		/// Returns the marginal distribution for 'bernoullies' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public DistributionStructArray<Bernoulli,bool> BernoulliesMarginal()
		{
			return this.bernoullies_marginal_F;
		}

		/// <summary>Computations that do not depend on observed values</summary>
		private void Constant()
		{
			if (this.Constant_isDone) {
				return ;
			}
			Bernoulli vBernoulli0 = Bernoulli.FromLogOdds(double.PositiveInfinity);
			// Create array for 'bernoullies_marginal' Forwards messages.
			this.bernoullies_marginal_F = new DistributionStructArray<Bernoulli,bool>(9);
			for(int _iv = 0; _iv<9; _iv++) {
				this.bernoullies_marginal_F[_iv] = Bernoulli.Uniform();
			}
			DistributionStructArray<Bernoulli,bool> bernoullies_use_B;
			// Create array for 'bernoullies_use' Backwards messages.
			bernoullies_use_B = new DistributionStructArray<Bernoulli,bool>(9);
			for(int _iv = 0; _iv<9; _iv++) {
				bernoullies_use_B[_iv] = Bernoulli.Uniform();
			}
			Bernoulli[][] bernoullies_uses_F;
			Bernoulli[][] bernoullies_uses_B;
			// Create array for 'bernoullies_uses' Forwards messages.
			bernoullies_uses_F = new Bernoulli[9][];
			// Create array for 'bernoullies_uses' Backwards messages.
			bernoullies_uses_B = new Bernoulli[9][];
			for(int _iv = 0; _iv<9; _iv++) {
				// Create array for 'bernoullies_uses' Forwards messages.
				bernoullies_uses_F[_iv] = new Bernoulli[2];
				bernoullies_uses_F[_iv][1] = Bernoulli.Uniform();
				bernoullies_uses_F[_iv][0] = Bernoulli.Uniform();
				// Create array for 'bernoullies_uses' Backwards messages.
				bernoullies_uses_B[_iv] = new Bernoulli[2];
				bernoullies_uses_B[_iv][1] = Bernoulli.Uniform();
				bernoullies_uses_B[_iv][0] = Bernoulli.Uniform();
			}
			// Message to 'bernoullies_marginal' from Variable factor
			this.bernoullies_marginal_F[0] = VariableOp.MarginalAverageConditional<Bernoulli>(bernoullies_use_B[0], vBernoulli0, this.bernoullies_marginal_F[0]);
			// Message to 'bernoullies_uses' from Replicate factor
			bernoullies_uses_F[0][0] = ReplicateOp_NoDivide.UsesAverageConditional<Bernoulli>(bernoullies_uses_B[0], vBernoulli0, 0, bernoullies_uses_F[0][0]);
			// Message to 'bernoullies_uses' from Replicate factor
			bernoullies_uses_F[0][1] = ReplicateOp_NoDivide.UsesAverageConditional<Bernoulli>(bernoullies_uses_B[0], vBernoulli0, 1, bernoullies_uses_F[0][1]);
			// Message to 'bernoullies_marginal' from Variable factor
			this.bernoullies_marginal_F[1] = VariableOp.MarginalAverageConditional<Bernoulli>(bernoullies_use_B[1], vBernoulli0, this.bernoullies_marginal_F[1]);
			// Message to 'bernoullies_uses' from Replicate factor
			bernoullies_uses_F[1][0] = ReplicateOp_NoDivide.UsesAverageConditional<Bernoulli>(bernoullies_uses_B[1], vBernoulli0, 0, bernoullies_uses_F[1][0]);
			// Message to 'bernoullies_uses' from Replicate factor
			bernoullies_uses_F[1][1] = ReplicateOp_NoDivide.UsesAverageConditional<Bernoulli>(bernoullies_uses_B[1], vBernoulli0, 1, bernoullies_uses_F[1][1]);
			// Message to 'bernoullies_marginal' from Variable factor
			this.bernoullies_marginal_F[2] = VariableOp.MarginalAverageConditional<Bernoulli>(bernoullies_use_B[2], vBernoulli0, this.bernoullies_marginal_F[2]);
			// Message to 'bernoullies_uses' from Replicate factor
			bernoullies_uses_F[2][0] = ReplicateOp_NoDivide.UsesAverageConditional<Bernoulli>(bernoullies_uses_B[2], vBernoulli0, 0, bernoullies_uses_F[2][0]);
			// Message to 'bernoullies_uses' from Replicate factor
			bernoullies_uses_F[2][1] = ReplicateOp_NoDivide.UsesAverageConditional<Bernoulli>(bernoullies_uses_B[2], vBernoulli0, 1, bernoullies_uses_F[2][1]);
			// Message to 'bernoullies_marginal' from Variable factor
			this.bernoullies_marginal_F[3] = VariableOp.MarginalAverageConditional<Bernoulli>(bernoullies_use_B[3], vBernoulli0, this.bernoullies_marginal_F[3]);
			// Message to 'bernoullies_uses' from Replicate factor
			bernoullies_uses_F[3][0] = ReplicateOp_NoDivide.UsesAverageConditional<Bernoulli>(bernoullies_uses_B[3], vBernoulli0, 0, bernoullies_uses_F[3][0]);
			// Message to 'bernoullies_uses' from Replicate factor
			bernoullies_uses_F[3][1] = ReplicateOp_NoDivide.UsesAverageConditional<Bernoulli>(bernoullies_uses_B[3], vBernoulli0, 1, bernoullies_uses_F[3][1]);
			// Message to 'bernoullies_marginal' from Variable factor
			this.bernoullies_marginal_F[4] = VariableOp.MarginalAverageConditional<Bernoulli>(bernoullies_use_B[4], vBernoulli0, this.bernoullies_marginal_F[4]);
			// Message to 'bernoullies_uses' from Replicate factor
			bernoullies_uses_F[4][0] = ReplicateOp_NoDivide.UsesAverageConditional<Bernoulli>(bernoullies_uses_B[4], vBernoulli0, 0, bernoullies_uses_F[4][0]);
			// Message to 'bernoullies_uses' from Replicate factor
			bernoullies_uses_F[4][1] = ReplicateOp_NoDivide.UsesAverageConditional<Bernoulli>(bernoullies_uses_B[4], vBernoulli0, 1, bernoullies_uses_F[4][1]);
			// Message to 'bernoullies_marginal' from Variable factor
			this.bernoullies_marginal_F[5] = VariableOp.MarginalAverageConditional<Bernoulli>(bernoullies_use_B[5], vBernoulli0, this.bernoullies_marginal_F[5]);
			// Message to 'bernoullies_uses' from Replicate factor
			bernoullies_uses_F[5][0] = ReplicateOp_NoDivide.UsesAverageConditional<Bernoulli>(bernoullies_uses_B[5], vBernoulli0, 0, bernoullies_uses_F[5][0]);
			// Message to 'bernoullies_uses' from Replicate factor
			bernoullies_uses_F[5][1] = ReplicateOp_NoDivide.UsesAverageConditional<Bernoulli>(bernoullies_uses_B[5], vBernoulli0, 1, bernoullies_uses_F[5][1]);
			// Message to 'bernoullies_marginal' from Variable factor
			this.bernoullies_marginal_F[6] = VariableOp.MarginalAverageConditional<Bernoulli>(bernoullies_use_B[6], vBernoulli0, this.bernoullies_marginal_F[6]);
			// Message to 'bernoullies_uses' from Replicate factor
			bernoullies_uses_F[6][0] = ReplicateOp_NoDivide.UsesAverageConditional<Bernoulli>(bernoullies_uses_B[6], vBernoulli0, 0, bernoullies_uses_F[6][0]);
			// Message to 'bernoullies_uses' from Replicate factor
			bernoullies_uses_F[6][1] = ReplicateOp_NoDivide.UsesAverageConditional<Bernoulli>(bernoullies_uses_B[6], vBernoulli0, 1, bernoullies_uses_F[6][1]);
			// Message to 'bernoullies_marginal' from Variable factor
			this.bernoullies_marginal_F[7] = VariableOp.MarginalAverageConditional<Bernoulli>(bernoullies_use_B[7], vBernoulli0, this.bernoullies_marginal_F[7]);
			// Message to 'bernoullies_uses' from Replicate factor
			bernoullies_uses_F[7][0] = ReplicateOp_NoDivide.UsesAverageConditional<Bernoulli>(bernoullies_uses_B[7], vBernoulli0, 0, bernoullies_uses_F[7][0]);
			// Message to 'bernoullies_uses' from Replicate factor
			bernoullies_uses_F[7][1] = ReplicateOp_NoDivide.UsesAverageConditional<Bernoulli>(bernoullies_uses_B[7], vBernoulli0, 1, bernoullies_uses_F[7][1]);
			// Message to 'bernoullies_marginal' from Variable factor
			this.bernoullies_marginal_F[8] = VariableOp.MarginalAverageConditional<Bernoulli>(bernoullies_use_B[8], vBernoulli0, this.bernoullies_marginal_F[8]);
			// Message to 'bernoullies_uses' from Replicate factor
			bernoullies_uses_F[8][0] = ReplicateOp_NoDivide.UsesAverageConditional<Bernoulli>(bernoullies_uses_B[8], vBernoulli0, 0, bernoullies_uses_F[8][0]);
			// Message to 'bernoullies_uses' from Replicate factor
			bernoullies_uses_F[8][1] = ReplicateOp_NoDivide.UsesAverageConditional<Bernoulli>(bernoullies_uses_B[8], vBernoulli0, 1, bernoullies_uses_F[8][1]);
			Bernoulli anyTrue_F = default(Bernoulli);
			DistributionStructArray<Bernoulli,bool> bernoullies_depth0_F;
			// Create array for 'bernoullies_depth0' Forwards messages.
			bernoullies_depth0_F = new DistributionStructArray<Bernoulli,bool>(9);
			for(int _iv = 0; _iv<9; _iv++) {
				bernoullies_depth0_F[_iv] = Bernoulli.Uniform();
				// Message to 'bernoullies_depth0' from Copy factor
				bernoullies_depth0_F[_iv] = ArrayHelper.SetTo<Bernoulli>(bernoullies_depth0_F[_iv], bernoullies_uses_F[_iv][0]);
			}
			this.anyTrue_marginal_F = Bernoulli.Uniform();
			Bernoulli anyTrue_use_B = Bernoulli.Uniform();
			// Message to 'anyTrue' from AllTrue factor
			anyTrue_F = AllTrueOp.AllTrueAverageConditional(bernoullies_depth0_F);
			// Message to 'anyTrue_marginal' from DerivedVariable factor
			this.anyTrue_marginal_F = DerivedVariableOp.MarginalAverageConditional<Bernoulli>(anyTrue_use_B, anyTrue_F, this.anyTrue_marginal_F);
			DistributionStructArray<Bernoulli,bool> vbool__1_F;
			// Create array for 'vbool__1' Forwards messages.
			vbool__1_F = new DistributionStructArray<Bernoulli,bool>(9);
			for(int bernolieRange = 0; bernolieRange<9; bernolieRange++) {
				vbool__1_F[bernolieRange] = Bernoulli.Uniform();
				// Message to 'vbool__1' from Not factor
				vbool__1_F[bernolieRange] = BooleanNotOp.NotAverageConditional(bernoullies_uses_F[bernolieRange][1]);
			}
			// Create array for 'vbool__1_marginal' Forwards messages.
			this.vbool__1_marginal_F = new DistributionStructArray<Bernoulli,bool>(9);
			DistributionStructArray<Bernoulli,bool> vbool__1_use_B;
			// Create array for 'vbool__1_use' Backwards messages.
			vbool__1_use_B = new DistributionStructArray<Bernoulli,bool>(9);
			for(int bernolieRange = 0; bernolieRange<9; bernolieRange++) {
				this.vbool__1_marginal_F[bernolieRange] = Bernoulli.Uniform();
				vbool__1_use_B[bernolieRange] = Bernoulli.Uniform();
				// Message to 'vbool__1_marginal' from DerivedVariable factor
				this.vbool__1_marginal_F[bernolieRange] = DerivedVariableOp.MarginalAverageConditional<Bernoulli>(vbool__1_use_B[bernolieRange], vbool__1_F[bernolieRange], this.vbool__1_marginal_F[bernolieRange]);
			}
			Bernoulli orTrue_F = default(Bernoulli);
			this.orTrue_marginal_F = Bernoulli.Uniform();
			Bernoulli orTrue_use_B = Bernoulli.Uniform();
			// Message to 'orTrue' from AllTrue factor
			orTrue_F = AllTrueOp.AllTrueAverageConditional(vbool__1_F);
			// Message to 'orTrue_marginal' from DerivedVariable factor
			this.orTrue_marginal_F = DerivedVariableOp.MarginalAverageConditional<Bernoulli>(orTrue_use_B, orTrue_F, this.orTrue_marginal_F);
			Bernoulli vbool28_F = default(Bernoulli);
			this.vbool28_marginal_F = Bernoulli.Uniform();
			Bernoulli vbool28_use_B = Bernoulli.Uniform();
			// Message to 'vbool28' from Not factor
			vbool28_F = BooleanNotOp.NotAverageConditional(orTrue_F);
			// Message to 'vbool28_marginal' from DerivedVariable factor
			this.vbool28_marginal_F = DerivedVariableOp.MarginalAverageConditional<Bernoulli>(vbool28_use_B, vbool28_F, this.vbool28_marginal_F);
			this.Constant_isDone = true;
		}

		/// <summary>Update all marginals, by iterating message passing the given number of times</summary>
		/// <param name="numberOfIterations">The number of times to iterate each loop</param>
		/// <param name="initialise">If true, messages that initialise loops are reset when observed values change</param>
		private void Execute(int numberOfIterations, bool initialise)
		{
			this.Constant();
			this.numberOfIterationsDone = numberOfIterations;
		}

		/// <summary>Update all marginals, by iterating message-passing the given number of times</summary>
		/// <param name="numberOfIterations">The total number of iterations that should be executed for the current set of observed values.  If this is more than the number already done, only the extra iterations are done.  If this is less than the number already done, message-passing is restarted from the beginning.  Changing the observed values resets the iteration count to 0.</param>
		public void Execute(int numberOfIterations)
		{
			this.Execute(numberOfIterations, true);
		}

		/// <summary>Get the observed value of the specified variable.</summary>
		/// <param name="variableName">Variable name</param>
		public object GetObservedValue(string variableName)
		{
			throw new ArgumentException("Not an observed variable name: "+variableName);
		}

		/// <summary>Get the marginal distribution (computed up to this point) of a variable</summary>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <returns>The marginal distribution computed up to this point</returns>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public object Marginal(string variableName)
		{
			if (variableName=="bernoullies") {
				return this.BernoulliesMarginal();
			}
			if (variableName=="anyTrue") {
				return this.AnyTrueMarginal();
			}
			if (variableName=="vbool__1") {
				return this.Vbool__1Marginal();
			}
			if (variableName=="orTrue") {
				return this.OrTrueMarginal();
			}
			if (variableName=="vbool28") {
				return this.Vbool28Marginal();
			}
			throw new ArgumentException("This class was not built to infer "+variableName);
		}

		/// <summary>Get the marginal distribution (computed up to this point) of a variable, converted to type T</summary>
		/// <typeparam name="T">The distribution type.</typeparam>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <returns>The marginal distribution computed up to this point</returns>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public T Marginal<T>(string variableName)
		{
			return Distribution.ChangeType<T>(this.Marginal(variableName));
		}

		/// <summary>Get the query-specific marginal distribution of a variable.</summary>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <param name="query">QueryType name. For example, GibbsSampling answers 'Marginal', 'Samples', and 'Conditionals' queries</param>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public object Marginal(string variableName, string query)
		{
			if (query=="Marginal") {
				return this.Marginal(variableName);
			}
			throw new ArgumentException(((("This class was not built to infer \'"+variableName)+"\' with query \'")+query)+"\'");
		}

		/// <summary>Get the query-specific marginal distribution of a variable, converted to type T</summary>
		/// <typeparam name="T">The distribution type.</typeparam>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <param name="query">QueryType name. For example, GibbsSampling answers 'Marginal', 'Samples', and 'Conditionals' queries</param>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public T Marginal<T>(string variableName, string query)
		{
			return Distribution.ChangeType<T>(this.Marginal(variableName, query));
		}

		private void OnProgressChanged(ProgressChangedEventArgs e)
		{
			// Make a temporary copy of the event to avoid a race condition
			// if the last subscriber unsubscribes immediately after the null check and before the event is raised.
			EventHandler<ProgressChangedEventArgs> handler = this.ProgressChanged;
			if (handler!=null) {
				handler(this, e);
			}
		}

		/// <summary>
		/// Returns the marginal distribution for 'orTrue' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public Bernoulli OrTrueMarginal()
		{
			return this.orTrue_marginal_F;
		}

		/// <summary>Reset all messages to their initial values.  Sets NumberOfIterationsDone to 0.</summary>
		public void Reset()
		{
			this.Execute(0);
		}

		/// <summary>Set the observed value of the specified variable.</summary>
		/// <param name="variableName">Variable name</param>
		/// <param name="value">Observed value</param>
		public void SetObservedValue(string variableName, object value)
		{
			throw new ArgumentException("Not an observed variable name: "+variableName);
		}

		/// <summary>Update all marginals, by iterating message-passing an additional number of times</summary>
		/// <param name="additionalIterations">The number of iterations that should be executed, starting from the current message state.  Messages are not reset, even if observed values have changed.</param>
		public void Update(int additionalIterations)
		{
			this.Execute(checked(this.numberOfIterationsDone+additionalIterations), false);
		}

		/// <summary>
		/// Returns the marginal distribution for 'vbool__1' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public DistributionStructArray<Bernoulli,bool> Vbool__1Marginal()
		{
			return this.vbool__1_marginal_F;
		}

		/// <summary>
		/// Returns the marginal distribution for 'vbool28' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public Bernoulli Vbool28Marginal()
		{
			return this.vbool28_marginal_F;
		}

		#endregion

		#region Events
		/// <summary>Event that is fired when the progress of inference changes, typically at the end of one iteration of the inference algorithm.</summary>
		public event EventHandler<ProgressChangedEventArgs> ProgressChanged;
		#endregion

	}

}
